{
 "title": "Injective Mainnet Network",
 "description": "chain_id - injective-1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Block Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Avg Number of TXs (per block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(cometbft_consensus_num_txs[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(cometbft_consensus_block_size_bytes[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of TXs (current block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_consensus_num_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg TX Size (mempool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Avg Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(cometbft_mempool_size[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Number of Validators Missing (per block)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(cometbft_consensus_missing_validators[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Validators Missing (in current block)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Duration (sum)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Failed TX Count (mempool)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_mempool_failed_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TX Recheck Count (mempool)",
   "type": "timeseries",
   "description": "Number of times transactions are rechecked in the mempool.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_mempool_recheck_times", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_consensus_rounds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "quorum_prevote_delay",
   "type": "timeseries",
   "description": "Interval in seconds between the proposal timestamp and the timestamp of the earliest prevote that achieved a quorum.",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cometbft_consensus_quorum_prevote_delay",
     "legendFormat": "proposer=\"{{proposer_address}}\""
    }
   ]
  },
  {
   "title": "p2p_message_receive_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(chain_id) (cometbft_p2p_message_receive_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p2p_message_send_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(chain_id) (cometbft_p2p_message_send_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consensus_block_gossip_parts_received",
   "type": "timeseries",
   "description": "Number of block parts received by the node, separated by whether the part was relevant to the block the node is trying to gather or not.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_gossip_parts_received",
     "legendFormat": "relevant_to_current_block = {{matches_current}}"
    }
   ]
  },
  {
   "title": "node peer_count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "p2p bandwidth per peer (experimental)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "($A + $B) / $C", "type": "math" }
   ]
  },
  {
   "title": "Avg quorum_prevote_delay",
   "type": "bargauge",
   "description": "Interval in seconds between the proposal timestamp and the timestamp of the earliest prevote that achieved a quorum.",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(proposer_address) (cometbft_consensus_quorum_prevote_delay)",
     "legendFormat": "proposer=\"{{proposer_address}}\""
    }
   ]
  }
 ]
}